[general]
import = [
    "~/.cache/wal/colors-alacritty.toml"
]


[font]
# normal = {family="Miracode",style="Regular"}
# size=11
normal = {family="Terminess Nerd Font Mono",style="Regular"}
size=12

[keyboard]
bindings = [
  { key = "Left",  mods = "Control",     chars = "\u001bB"   },
  { key = "Right", mods = "Control",     chars = "\u001bF"   },
  { key = "Back",  mods = "Control", chars = "\u001b\u007f"    },
]
